api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

#Rutas automáticas con router:
# Ruta	Descripción
# /api/accounts/	Listado de cuentas (del cliente autenticado)
# /api/accounts/<pk>/	Detalle de cuenta
# /api/transactions/	Listado de transacciones (del cliente autenticado)
# /api/transactions/<pk>/	Detalle de transacción
# /api/cards/	Listado de tarjetas (del cliente autenticado)
# /api/cards/<pk>/	Detalle de tarjeta
router = routers.DefaultRouter()
router.register('accounts', views.AccountViewSet)
router.register('transactions', views.TransactionViewSet)
router.register('cards', views.CreditCardViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from clients import views as cliente
from django.conf.urls.i18n import i18n_patterns

#Listado donde se almacenan todas las urls.
urlpatterns = []

# Url que no se deben internacionalizar.
urlpatterns_base = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
]

# Utilizando i18n_patterns para aplicar la internacionalización a las URL de clientes, transacciones y otras...
urlpatterns += i18n_patterns(
    path('', cliente.dashboard, name='home'),
    path('', include('clients.urls')),
    path('', include('transactions.urls')),
    path('', include('django.contrib.auth.urls')),
)

# Se combinan ambas tanto internacionalizadas como las que no, pero añadimos las no internacionalizadas al final
urlpatterns += urlpatterns_base

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bank_odpcs/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from account import views as acc_view

urlpatterns = [
    path('', acc_view.dashboard, name='HOME'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cards/', include('cards.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'clients'
urlpatterns = [

    path('', views.dashboard, name='home'),
    path('register/', views.register, name='register'),
    path('accounts/', views.accounts, name='accounts'),
    path('account-details/<int:account_id>/', views.account_details, name='account-details'),
    path('add-money/<int:account_id>/', views.add_money, name='add-money'),
    path('deactivate/<int:account_id>/', views.deactivate_account, name='deactivate'),
    path('reactivate/<str:token>/', views.reactivate_account, name='reactivate'),
    path('edit-alias/<int:account_id>/', views.edit_alias, name='edit-alias'),
   
    
    # URLs relacionadas con tarjetas
    path('list_cards/', views.credit_card_list, name='credit_card_list'),
    path('my_cards/', views.credit_cards, name='credit_cards'),
    path('add/', views.add_credit_card, name='add_credit_card'),
    path('add-wa/<str:account_id>/', views.add_credit_card_without_account, name='add_credit_card_without_account'),
    path('block/<str:card_code>/', views.block_credit_card, name='block_credit_card'),
    path('unblock/<str:card_code>/', views.reactivate_credit_card, name='reactivate_credit_card'),
    path('delete/<str:card_code>/', views.delete_credit_card, name='delete_credit_card'),

    # URLs relacionadas con cuentas
    path('register-account/', views.client_register, name='client_register'),
    path('login/', views.client_login, name='login'),
    path('accounts/', views.accounts, name='accounts'),
    path('profile/', views.profile, name='profile'),
    path('edit/', views.edit, name='edit'),
    path('account-details/<int:account_id>/', views.account_details, name='account_details'),
    path('add-money/<int:account_id>/', views.add_money, name='add_money'),
    path('edit-alias/<int:account_id>/', views.edit_alias, name='edit_alias'),
    path('deactivate-client/<int:client_id>/', views.deactivate_client, name='deactivate_client'),
    path('client/reactivate/<str:token>/', views.reactivate_client, name='reactivate'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

transactions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'transactions'
urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('transfer/incoming/', views.incoming, name='incoming'),
    path('transfer/outcoming/', views.outcoming, name='outcoming'),
    path('movements/', views.movements, name='movements'),
    path('movements/export-csv/', views.export_transactions_csv, name='export_transactions_csv'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

clients/views.py
import json
from django.utils.translation import gettext as _
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.crypto import get_random_string
from django.contrib.auth.hashers import make_password
from .forms import AccountRegistrationForm, AddMoneyForm, ClientEditForm, ClientRegistrationForm, CreditCardForm, CreditCardFormWithoutAccount, LoginForm, UserEditForm, UserRegistrationForm
from .models import Account, Client, CreditCard 
from transactions.models import Transaction

#######################################################



# Cuentas

@login_required
def register(request):
    current_account_count = Account.objects.filter(client=request.user.client).count()
    if current_account_count >= 3:
        messages.error(request,  _('Número máximo de cuentas excedido (máximo 3 cuentas).'))
        return redirect('home')

    if request.method == 'POST':
        form = AccountRegistrationForm(request.POST)
        if form.is_valid():
            user = authenticate(username=request.user.username, password=form.cleaned_data['password'])
            if user is not None:
                account = form.save(commit=False)
                account.client = request.user.client
                account.save()
                return redirect('home')
            else:
                messages.error(request, _('La contraseña actual ingresada no es correcta.'))
    else:
        form = AccountRegistrationForm()

    return render(request, 'account/register.html', {'form': form})

@login_required
def accounts(request):
    accounts = Account.objects.filter(client=request.user.client, status=Account.Status.ACTIVE)
    return render(request, 'account/accounts.html', {'accounts': accounts})

@login_required
def account_details(request, account_id):
    account = get_object_or_404(Account, id=account_id)
    transactions = Transaction.objects.filter(account=account).order_by('-timestamp')
    credit_cards = account.credit_cards.all()
    return render(request, 'account/account_details.html', {'account': account,'transactions': transactions, 'credit_cards': credit_cards})

@login_required
def add_money(request, account_id):
    account = get_object_or_404(Account, id=account_id)
    if request.method == 'POST':
        form = AddMoneyForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            if amount <= 1000000:
                if account.balance < 999999999.99:
                    account.balance += amount
                    account.save()
                else:
                    form.add_error('amount', _('La cantidad que ha puesto excede el límite que puede alvergar la cuenta.'))
                alias=account.alias
                balance=account.balance
                messages.success(request, _(f'Se han añadido {amount} euros a la cuenta {alias}. Balance actual: {balance} euros.'))
                return redirect('clients:account_details', account_id=account.id)
            else:
                form.add_error('amount', _('La cantidad no puede superar 1 millón de euros.')) 
    else:
        form = AddMoneyForm()

    return render(request, 'account/add_money.html', {'form': form, 'account': account})  
@login_required
def edit(request):
    if request.method == 'POST':
        client_form = ClientEditForm(
            instance=request.user.client, files=request.FILES, data=request.POST
        )
        print(request.FILES)
        user_form = UserEditForm(instance=request.user, data=request.POST)

        if client_form.is_valid() and user_form.is_valid():
            client_form.save()
            user_form.save()
            messages.success(request, _('¡ Perfil actualizado correctamente !'))
            return render(request, 'client/profile.html', {'profile': profile})
        else:
            messages.error(request, _('Error al actualizar tu perfil'))
    else:
        client_form = ClientEditForm(instance=request.user.client)
        user_form = UserEditForm(instance=request.user)
        print("\n\n\n\n\n\n\n\n\n   ",request.user.client)
        photo = request.user.client

    return render(
        request,
        'client/edit.html',
        {'client_form': client_form, 'user_form': user_form, 'photo': photo},
    )

@login_required
def edit_alias(request, account_id):
    account = get_object_or_404(Account, id=account_id)

    if request.method == 'POST':
        new_alias = request.POST.get('new_alias')
        account.alias = new_alias
        account.save()
        messages.success(request, _('El alias de la cuenta se ha cambiado correctamente.'))
        return redirect('home')
    else:
        return render(request, 'account/edit_alias.html', {'account': account})

@login_required
def deactivate_account(request, account_id):
    if request.method == 'POST':
        account = get_object_or_404(Account, id=account_id, client=request.user.client)

        if account.status == Account.Status.BLOCK:
            messages.warning(request, _('La cuenta ya está desactivada.'))
            return redirect('home')

        account.status = Account.Status.BLOCK
        account.save()

        reactivation_token = get_random_string(length=32)
        account.reactivation_token = reactivation_token
        account.save()

        subject = _('Reactiva tu cuenta')
        message = _(f'Pulsa en el enlace para reactivar tu cuenta: http://localhost:8000/es/reactivate/{reactivation_token}')
        from_email = 'your_email@example.com'
        to_list = [request.user.email]

        send_mail(subject, message, from_email, to_list, fail_silently=True)

        return redirect('home')

    return render(request, 'account/deactivate_account.html')

@login_required
def reactivate_account(request, token):
    account = Account.objects.filter(reactivation_token=token, status=Account.Status.BLOCK).first()
    
    if account:
        account.status = Account.Status.ACTIVE
        account.reactivation_token = None
        account.save()
        return render(request, 'account/reactivate_account.html', {'success': True})
    
    return render(request, 'account/reactivate_account.html', {'success': False})




#######################################################




# Tarjetas

@login_required
def credit_card_list(request):
    credit_cards = CreditCard.objects.all()
    return render(request, 'cards/credit_card_list.html', {'credit_cards': credit_cards})

@login_required
def credit_cards(request):
    account_id = request.GET.get('account_id')
    status = request.GET.get('status')

    accounts = Account.objects.filter(client=request.user.client)

    if account_id:
        credit_cards = CreditCard.objects.filter(account_id=account_id, status=status)
    else:
        credit_cards = CreditCard.objects.none()

    return render(request, 'cards/credit_cards.html', {'credit_cards': credit_cards, 'accounts': accounts})

@login_required
def add_credit_card(request):
    card_count = CreditCard.objects.filter(account__client=request.user.client).count()
    
    if card_count >= 4:
        messages.error(request, _('Has alcanzado el límite máximo de tarjetas de crédito.'))
        return redirect('clients:home')

    if request.method == 'POST':
        form = CreditCardForm(request.user.client, request.POST)
        if form.is_valid():
            credit_card = form.save(commit=False)
            credit_card.account = form.cleaned_data['account']
            pin = credit_card.pin
            credit_card.pin = make_password(pin)
            credit_card.save()
            codigo=credit_card.card_code

            send_mail(
                _(f'Tu tarjeta {codigo} ha sido creada con éxito'),
                _(f'Este es tu PIN: {pin}'),
                'your_email@example.com',
                [request.user.email],
                fail_silently=False,
            )
            return redirect('clients:credit_cards')
    else:
        form = CreditCardForm(request.user.client)

    return render(request, 'cards/add_credit_card.html', {'form': form})

@login_required
def add_credit_card_without_account(request, account_id):
    account = get_object_or_404(Account, id=account_id)
    card_count = CreditCard.objects.filter(account=account).count()

    if card_count >= 4:
        messages.error(request, _('Has alcanzado el límite máximo de tarjetas de crédito.'))
        return redirect('home')

    if request.method == 'POST':
        form = CreditCardFormWithoutAccount(request.POST)
        if form.is_valid():
            credit_card = form.save(commit=False)
            credit_card.account = account
            pin = credit_card.pin
            credit_card.pin = make_password(pin)
            credit_card.save()
            codigo =credit_card.card_code
            send_mail(
                _(f'Tu tarjeta {codigo} ha sido creada con éxito'),
                _(f'Este es tu PIN: {pin}'),
                'your_email@example.com',
                [request.user.email],
                fail_silently=True,
            )
            messages.success(request, _("Se ha creado la tarjeta con éxito"))
            return redirect('clients:account_details', account_id=account.id)
    else:
        form = CreditCardFormWithoutAccount()

    return render(request, 'cards/add_credit_card.html', {'form': form})

@login_required
def block_credit_card(request, card_code):
    card = get_object_or_404(CreditCard, card_code=card_code)
    
    if card.account.client.user == request.user:
        if card.status == CreditCard.Status.BLOCK:
            messages.error(request, _('Esta tarjeta ya está bloqueada.'))
            return redirect('home')

        card.status = CreditCard.Status.BLOCK
        card.save()

        send_mail(

clients/templates/base.html
{% load static %}
{% load thumbnail %}
{% load i18n %}
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}Bank ODPCS{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body style="background-color: #92c6ce;">
  
  <nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="/es/">BankODPCS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link text-white" href="{% url 'home' %}">{% trans "Inicio" %} <span class="sr-only">({% trans "Actual"%})</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'clients:credit_cards' %}">{% trans "Tarjetas" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'transactions:payment' %}">{% trans "Pagos" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'transactions:movements' %}">{% trans "Transferencias" %}</a>
        </li>
        <li class="nav-item">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          <form class="nav-link  " name="form">
            <select class="form-select bg-outline-info" name="opciones" onchange="location.href=form.opciones.value;">
              {% for language in languages %}
                <option value="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %}selected{% endif %}>
                {{ language.name_local }}
                </option>
              {% endfor %}
            </select>
          </form>
        </li>
      </ul>
    </div>
    <span class="user">
      {% if request.user.is_authenticated %}
      {% trans "Hola" %} <a href="{% url 'clients:profile' %}">
        {% if request.user.client.photo %}
            <img src="{% thumbnail request.user.client.photo 35x35 %}" class="user-detail">
        {% else %}
            <img src="{% static '../media/no_picture.png' %}" class="user-detail" style="width: 30px;">
        {% endif %}
        </a> | 
          <form method="post" action="{% url 'logout' %}" style="display: inline;">
              {% csrf_token %}
              <button type="submit" style="border: none; background: none; padding: 0; color: #f0a93e; cursor: pointer;">{% trans "Cerrar sesión" %}</button>
          </form>
      {% else %}
          <a href="{% url 'login' %}">{% trans "Iniciar sesión" %}</a>
      {% endif %}
    </span>
  </nav>
  
  <main>
    {% block content %}{% endblock %}
  </main>
  <footer>
    <section class="top">
      <ul>
        <li>
          <h3>{% trans "Productos" %}</h3>
          <a>{% trans "Cuentas" %}</a>
          <a>{% trans "Tarjetas" %}</a>
        </li>
        <li>
          <h3>{% trans "BankODPCS" %}</h3>
          <a>{% trans "Sobre nosotros" %}</a>
          <a>{% trans "Bancos socios" %}</a>
          <a>{% trans "Ayuda" %}</a>
        </li>
      </ul>
    </section>
    
    <section>
      <div class="row">
        <div class="col">
          <img class="image"src="../../../media/dibujo.svg" class="section-image" />

        </div>
      </div>
      <div class="row"> 
        <div class="col">
            <section class="bottom">2023 BANK ODPCS. Todos los derechos reservados.</section>
        </div>

      </div>
    </section>

    
  </footer>
</body>
<style>
  
  footer {
    padding: 10px 20px;
    display: flex;
    width: 100%;
    justify-content: space-between;
    z-index: 5;
    padding-bottom: 20px;
    background: #0a1535;
    color: #f9f9f9;
  }
  
  footer section {
    padding: 0 50px;
    text-align: center;
  }
  
  section.top {
    padding-top: 30px;
    margin-bottom: 48px;
    width: 100%;
  }
  
  .image{
    width: 100px;
    margin-left: 50;
  }
  
  section.top ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: grid;
    gap: 30px;
    grid-template-columns: repeat(2, 1fr);
  }
  
  @media (width > 600px) {
    section.top ul {
      grid-template-columns: repeat(2, 1fr);
      padding-right: 0;
    }
  }
  
  section.top ul li a {
    display: block;
    margin-bottom: 10px;
    color: rgb(255 255 255 / 90%);
  }
  
  section.top h3 {
    color: rgb(255 255 255 / 40%);
    font-weight: 400;
    text-transform: uppercase;
    font-size: 12px;
    letter-spacing: 1px;
  }
  
  section.bottom {
    padding-top: 10px;
    border-top: 2px solid rgb(255 255 255 / 10%);
    color: rgb(255 255 255 / 40%);
    font-size: 13px;
    
  }
  
</style>

</html>