api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

#Rutas automáticas con router:
# Ruta	Descripción
# /api/accounts/	Listado de cuentas (del cliente autenticado)
# /api/accounts/<pk>/	Detalle de cuenta
# /api/transactions/	Listado de transacciones (del cliente autenticado)
# /api/transactions/<pk>/	Detalle de transacción
# /api/cards/	Listado de tarjetas (del cliente autenticado)
# /api/cards/<pk>/	Detalle de tarjeta
router = routers.DefaultRouter()
router.register('accounts', views.AccountViewSet)
router.register('transactions', views.TransactionViewSet)
router.register('cards', views.CreditCardViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from clients import views as cliente
from django.conf.urls.i18n import i18n_patterns

#Listado donde se almacenan todas las urls.
urlpatterns = []

# Url que no se deben internacionalizar.
urlpatterns_base = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
]

# Utilizando i18n_patterns para aplicar la internacionalización a las URL de clientes, transacciones y otras...
urlpatterns += i18n_patterns(
    path('', cliente.dashboard, name='home'),
    path('', include('clients.urls')),
    path('', include('transactions.urls')),
    path('', include('django.contrib.auth.urls')),
)

# Se combinan ambas tanto internacionalizadas como las que no, pero añadimos las no internacionalizadas al final
urlpatterns += urlpatterns_base

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bank_odpcs/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from account import views as acc_view

urlpatterns = [
    path('', acc_view.dashboard, name='HOME'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cards/', include('cards.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'transactions'
urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('transfer/incoming/', views.incoming, name='incoming'),
    path('transfer/outcoming/', views.outcoming, name='outcoming'),
    path('movements/', views.movements, name='movements'),
    path('movements/export-csv/', views.export_transactions_csv, name='export_transactions_csv'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

transactions/models.py
from django.db import models

from clients.models import Account

# ┌───────────────────────┐
# │   Transactions        │
# ├───────────────────────┤
# │  agent                │
# │  concept              │
# │  timestamp            │
# │  amount               │
# │  kind                 │
# └───────────────────────┘


class Transaction(models.Model):
    KIND_CHOICES = [
        ('INCOMING', 'Incoming Transfer'),
        ('OUTGOING', 'Outgoing Transfer'),
        ('PAYMENT', 'Payment'),
    ]

    agent = models.CharField(max_length=20)
    concept = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    kind = models.CharField(max_length=20, choices=KIND_CHOICES)
    account = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name='transactions', null=True
    )

    def __str__(self):
        return f'{self.kind} - {self.agent} - {self.amount}'

transactions/forms.py
from django import forms
from transactions.models import Transaction


class PaymentForm(forms.Form):
    business = forms.CharField(required=True)
    ccc = forms.CharField(required=True)
    pin = forms.CharField(widget=forms.PasswordInput, required=True)
    amount = forms.DecimalField(required=True)

class TransferForm(forms.Form):
    sender = forms.CharField(required=True)
    cac = forms.CharField(required=True)
    concept = forms.CharField(required=True)
    amount = forms.DecimalField(required=True)

transactions/views.py
import csv
import datetime
from decimal import Decimal
import json
import django
import requests
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.http import (
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotFound,
)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt

from clients.models import Account, CreditCard

from .commisions import calcular_comision
from .forms import PaymentForm, TransferForm
from .models import Transaction
from django.template.loader import render_to_string
from weasyprint import HTML


@login_required
@csrf_exempt
def payment(request):
    if request.method == 'POST':
        # Obtener los datos del POST request
        try:
            data = json.loads(request.body)
        except json.JSONDecodeError:
            form = PaymentForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
            else:
                return HttpResponseForbidden(_(f"Datos del formulario invalido"))
        business = data.get('business')
        ccc = data.get('ccc')
        pin = data.get('pin')
        amount = data.get('amount')

        try:
            credit_card = CreditCard.objects.get(card_code=ccc)
        except CreditCard.DoesNotExist:
            return HttpResponseForbidden(
                _(f"La tarjeta '{ccc}' no existe o no coincide con ninguna tarjeta")
            )

        if not check_password(pin, credit_card.pin):
            return HttpResponseForbidden(_('El código PIN no coincide'))
        try:
            # Realizar el pago y actualizar el balance de la tarjeta
            comision = calcular_comision("salida", float(amount))
            print()
            credit_card.account.balance -= amount + comision
            print(credit_card.account)
            credit_card.account.save()

            # Crear registro de la transacción
            Transaction.objects.create(
                agent=business,
                concept="PAYMENT",
                amount=amount + comision,
                kind='PAYMENT',
                account=credit_card.account,
            )

            return HttpResponse("Ok!")
        except django.db.utils.IntegrityError:
            return HttpResponseNotFound(_("No tienes suficiente dinero para el pago"))
    else:
        accounts = Account.objects.filter(client=request.user.client)
        return render(request, 'payments/payments_form.html', {'accounts': accounts})

def generate_pdf(transaction):
    context = {'transaction': transaction}
    html_content = render_to_string('pdf/justificante_template.html', context)
    pdf_content = HTML(string=html_content).write_pdf()

    return pdf_content

@login_required
@csrf_exempt
def outcoming(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
        except json.JSONDecodeError:
            form = TransferForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
            else:
                return HttpResponseForbidden(_(f"Formato de datos del formulario no válido"))
        sender = data.get('sender')
        cac = data.get('cac')
        concept = data.get('concept')
        amount = data.get('amount')
        # print(data, sender, cac, concept)
        # Comprobar si la cuenta (cac) existe en la base de datos
        try:
            print(cac)
            account = Account.objects.get(code=sender, status="AC")
        except Account.DoesNotExist:
            # Si la cuenta no existe en la base de datos, usar la cuenta actual del usuario

            selected_account_alias = data.get('sender')

            account = get_object_or_404(Account, alias=selected_account_alias, client=request.user.client)

        comision = calcular_comision("salida", float(amount))
        # print(account, account.balance)
        if account.balance < (amount + comision):
            return HttpResponse(_("No hay suficiente dinero para realizar una transferencia"))

        url_banks = 'https://raw.githubusercontent.com/sdelquin/dsw/main/ut3/te1/notes/files/banks.json'
        response = requests.get(url_banks)
        banks = response.json()
        # print(banks)
        for bank in banks:
            if bank.get("id") == int(cac[1]):
                url = bank.get("url")

        # Enviar la solicitud POST al banco 2 para registrar la transacción entrante
        bank2_url = url + "/es/transfer/incoming/"
        # prueba_urllocal= "http://0.0.0.0:8000/transfer/incoming/"
        # bank2_url = "http://192.168.1.42:8000/transfer/incoming/"
        payload = {"sender": sender, "cac": cac, "concept": concept, "amount": str(amount)}
        print(payload)
        response = requests.post(bank2_url, json=payload)
        # print(bank2_url, payload)
        # print(response.status_code)
        if response.status_code == 200:

            account.balance -= amount + comision
            account.save()
            transaction = Transaction.objects.create(
                agent=sender, amount=(amount + comision), kind='OUTGOING', concept=concept, account=account
            )

            # Generar el justificante en PDF
            pdf_content = generate_pdf(transaction)

            # Devolver el PDF como respuesta
            response = HttpResponse(pdf_content, content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="justificante_{transaction.id}.pdf"'
            return response
        else:
            print(response.status_code)
            return HttpResponse({_("La transacción al banco falló")})
    else:
        accounts = Account.objects.filter(client=request.user.client)

        return render(request, 'transfers/transference_form.html', {'accounts': accounts})

@csrf_exempt
def incoming(request):
    if request.method == 'POST':
        # Obtener los datos del POST request
        data = json.loads(request.body)
        # Lista de datos a recoger
        sender = data.get("sender")
        cac = data.get('cac')
        concept = data.get('concept')
        amount = data.get('amount')
        print(sender,cac)
        try:
            account = Account.objects.get(code=cac, status="AC")
        except Account.DoesNotExist:
            return HttpResponseForbidden(_(f"La cuenta '{cac}' no existe o no está activa"))

        # Realizar la transferencia y actualizar el balance de la cuenta
        comision = calcular_comision("entrada", Decimal(amount))
        account.balance += Decimal(amount) - comision
        account.save()

        # Crear la transacción
        Transaction.objects.create(
            agent=sender, amount=(Decimal(amount)- comision), kind='INCOMING', concept=concept , account=account
        )

        return HttpResponse("Ok!", status=200)
    else:
        return HttpResponseNotFound(_("Error en la transferencia entrante"))

@login_required
def movements(request):
    # Obtener todas las cuentas bancarias del usuario actual
    accounts = Account.objects.filter(client=request.user.client, status=Account.Status.ACTIVE)

    # Filtrado por cuenta
    account_id = request.GET.get('account_id', '')
    if account_id:
        transactions = Transaction.objects.filter(account__code=account_id)
    else:
        # Si no se especifica una cuenta, mostrar todas las transacciones del usuario
        transactions = Transaction.objects.filter(account__in=accounts)

    # Filtrado por tipo de transacción
    transaction_type = request.GET.get('transaction_type', '')
    if transaction_type:
        transactions = transactions.filter(kind=transaction_type)

    transactions = transactions.order_by('-timestamp')

    # Paginación
    paginator = Paginator(transactions, 5)
    page = request.GET.get('page', 1)
    try:
        transactions = paginator.page(page)
    except PageNotAnInteger:
        transactions = paginator.page(1)
    except EmptyPage:
        transactions = paginator.page(paginator.num_pages)

    return render(request, 'transfers/movements.html', {'transactions': transactions, 'accounts': accounts})


# exportación de CSV
def export_transactions_csv(request):
    # Obtener el cliente actual del usuario
    current_client = request.user.client

    # Obtener la cuenta actual del cliente
    current_account = current_client.account_set.first()

    # Obtener solo las transacciones de la cuenta actual
    transactions = Transaction.objects.filter(account=current_account)

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="transactions.csv"'

    writer = csv.writer(response)
    fields = ['kind', 'agent', 'concept', 'timestamp', 'amount']

    # Escribir la primera fila con la información del encabezado
    writer.writerow([Transaction._meta.get_field(field).verbose_name for field in fields])

    # Escribir las filas de datos
    for transaction in transactions:
        data_row = [getattr(transaction, field) for field in fields]
        # Convertir campos de fecha a formato legible
        for i, field in enumerate(fields):
            if isinstance(getattr(transaction, field), datetime.datetime):
                data_row[i] = getattr(transaction, field).strftime('%d/%m/%Y')
        writer.writerow(data_row)

    return response

transactions/templates/transfers/list.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{% trans "Tipo de transferencia" %}</th>
                    <th>{% trans "Agente" %}</th>
                    <th>{% trans "Concepto" %}</th>
                    <th>{% trans "Fecha" %}</th>
                    <th>{% trans "Cantidad" %}</th>
                </tr>
            </thead>
            <tbody>
                {% if transactions %}
                    {% for transaction in transactions %}
                        <tr>
                            <td>{{ transaction.kind }}</td>
                            <td>{{ transaction.agent }}</td>
                            <td>{{ transaction.concept }}</td>
                            <td>{{ transaction.timestamp }}</td>
                            <td>{{ transaction.amount }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5">Todavia no hay transferencias</td>
                    </tr>
                {% endif %}
            </tbody>
            
        </table>
    </div>

    
</div>
{% endblock %}

transactions/templates/transfers/movements.html
<!-- movements.html -->
{% extends "base.html" %}
{% load i18n %}
{% block title %}Transaction List{% endblock %}

{% block content %}
<!-- Botón o enlace para exportar a CSV -->

<div class="container mt-5 mb-5">

    <div class="card">
        <div class="card-header">
            <h4 class="d-flex justify-content-between align-items-center mb-0">
                <span>{% trans "Transferencia"%}</span>
            </h4>
            <!-- Agregar un botón para dirigir al usuario a la página de transferencia -->
            <a href="{% url 'transactions:outcoming' %}"><button class="transferBtn">{% trans "Realizar transferencia" %}</button></a>
            <a href="{% url 'transactions:export_transactions_csv' %}"><button class="transferBtn">{% trans "Exportar a CSV"%}</button></a>            
        </div>
        <div class="card-body p-4">
            <!-- Filtro -->
            <form method="get" action="{% url 'transactions:movements' %}">
                <label for="account_id">{% trans "Cuenta:" %}</label>
                <select name="account_id">
                    <option value="">{% trans "Todas" %}</option>
                    {% for account in accounts %}
                    <option value="{{ account.code }}" {% if account.code == account_id %}selected{% endif %}>{{account.alias }}</option>
                    {% endfor %}
                </select>

                <label for="transaction_type">{% trans "Tipo de transaccion:" %}</label>
                <select name="transaction_type">
                    <option value="">{% trans "Todas" %}</option>
                    <option value="INCOMING" {% if transaction_type == 'INCOMING' %}selected{% endif %}>{% trans "Entrantes" %}</option>
                    <option value="OUTGOING" {% if transaction_type == 'OUTGOING' %}selected{% endif %}>{% trans "Salientes" %}</option>
                    <option value="PAYMENT" {% if transaction_type == 'PAYMENT' %}selected{% endif %}>{% trans "Pagos" %}</option>
                </select>

                <button type="submit">{% trans "Filtrar" %}</button>
            </form>
        </div>

        <!-- Lista de Transacciones -->
        <table>
            <thead>
                <tr>
                    <th>{% trans "Tipo de transferencia:" %}</th>
                    <th>{% trans "Agente" %}</th>
                    <th>{% trans "Concepto" %}</th>
                    <th>{% trans "Fecha" %}</th>
                    <th>{% trans "Cantidad" %}</th>
                </tr> 
            </thead>
            <tbody>
                {% if transactions %}
                    {% for transaction in transactions %}
                        <tr>
                            <td>{{ transaction.kind }}</td>
                            <td>{{ transaction.agent }}</td>
                            <td>{{ transaction.concept }}</td>
                            <td>{{ transaction.timestamp }}</td>
                            <td>{{ transaction.amount }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5" style="text-align: center;"><strong>Todavia no hay transferencias</strong></td>
                    </tr>
                {% endif %}
            </tbody>
        </table>


        <!-- Paginación -->
        <div class="pagination">
            <span class="step-links">
                {% if transactions.has_previous %}
                <a href="?page=1">&laquo; {% trans "Primera"%}</a>
                <a href="?page={{ transactions.previous_page_number }}">{% trans "Anterior" %}</a>
                {% endif %}

                <span class="current">
                    {% trans "Página" %} {{ transactions.number }} {% trans "de" %} {{ transactions.paginator.num_pages }}.
                </span>

                {% if transactions.has_next %}
                <a href="?page={{ transactions.next_page_number }}">{% trans "Siguente" %}</a>
                <a href="?page={{ transactions.paginator.num_pages }}">{% trans "Última" %} &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
<style>
    /* Style for pagination */
.pagination {
    display: flex;
    justify-content: center;
    align-items: center;
    list-style: none;
    padding: 0;
  }
  
  .pagination a {
    margin: 0 5px;
    text-decoration: none;
    color: #007bff; /* Change color as needed */
  }
  
  .pagination .current {
    margin: 0 5px;
    font-weight: bold;
  }
  
</style>
{% endblock %}

transactions/templates/transfers/transference_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="card">
        <div class="card-header">
            <h4 class="d-flex justify-content-between align-items-center mb-0">
                {% trans "Transferencia" %}
            </h4>
        </div>
        <div class="card-body p-4">
            <form method="post"  action="{% url 'transactions:outcoming' %}">
                {% csrf_token %}
                <div class="mb-4">
                    <select name="sender" class="form-select" placeholder="{% trans "Selecciona una cuenta" %}" required>
                        <option value="">{% trans "Selecciona una cuenta" %}</option>
                        {% for account in accounts %}
                            <option value="{{ account.code }}"> {{ account.alias }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-4">
                    <label for="cac" class="form-label">{% trans "Código de cuenta cliente (CAC)" %}</label>
                    <input type="text" id="cac" name="cac" class="form-control" placeholder="{% trans "Introduce el Código de la cuenta AX-XXXX" %}" required>
                </div>
                <div class="mb-4">
                    <label for="concept" class="form-label">{% trans "Concepto" %}</label>
                    <input type="text" id="concept" name="concept" class="form-control" placeholder="{% trans "Introduce el concepto" %}" required>
                </div>
                <div class="mb-4">
                    <label for="amount" class="form-label">{% trans "Cantidad" %}</label>
                    <input type="number" min="0.01" step="0.01" id="amount" name="amount" class="form-control" placeholder="{% trans "Introduce la cantidad" %}" required>
                </div>
                <button type="submit" class="transactButton">{% trans "Hacer transacción" %}</button>
            </form>

        </div>
    </div>
</div>
{% endblock %}