api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

#Rutas automáticas con router:
# Ruta	Descripción
# /api/accounts/	Listado de cuentas (del cliente autenticado)
# /api/accounts/<pk>/	Detalle de cuenta
# /api/transactions/	Listado de transacciones (del cliente autenticado)
# /api/transactions/<pk>/	Detalle de transacción
# /api/cards/	Listado de tarjetas (del cliente autenticado)
# /api/cards/<pk>/	Detalle de tarjeta
router = routers.DefaultRouter()
router.register('accounts', views.AccountViewSet)
router.register('transactions', views.TransactionViewSet)
router.register('cards', views.CreditCardViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from clients import views as cliente
from django.conf.urls.i18n import i18n_patterns

#Listado donde se almacenan todas las urls.
urlpatterns = []

# Url que no se deben internacionalizar.
urlpatterns_base = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
]

# Utilizando i18n_patterns para aplicar la internacionalización a las URL de clientes, transacciones y otras...
urlpatterns += i18n_patterns(
    path('', cliente.dashboard, name='home'),
    path('', include('clients.urls')),
    path('', include('transactions.urls')),
    path('', include('django.contrib.auth.urls')),
)

# Se combinan ambas tanto internacionalizadas como las que no, pero añadimos las no internacionalizadas al final
urlpatterns += urlpatterns_base

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bank_odpcs/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from account import views as acc_view

urlpatterns = [
    path('', acc_view.dashboard, name='HOME'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cards/', include('cards.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'clients'
urlpatterns = [

    path('', views.dashboard, name='home'),
    path('register/', views.register, name='register'),
    path('accounts/', views.accounts, name='accounts'),
    path('account-details/<int:account_id>/', views.account_details, name='account-details'),
    path('add-money/<int:account_id>/', views.add_money, name='add-money'),
    path('deactivate/<int:account_id>/', views.deactivate_account, name='deactivate'),
    path('reactivate/<str:token>/', views.reactivate_account, name='reactivate'),
    path('edit-alias/<int:account_id>/', views.edit_alias, name='edit-alias'),
   
    
    # URLs relacionadas con tarjetas
    path('list_cards/', views.credit_card_list, name='credit_card_list'),
    path('my_cards/', views.credit_cards, name='credit_cards'),
    path('add/', views.add_credit_card, name='add_credit_card'),
    path('add-wa/<str:account_id>/', views.add_credit_card_without_account, name='add_credit_card_without_account'),
    path('block/<str:card_code>/', views.block_credit_card, name='block_credit_card'),
    path('unblock/<str:card_code>/', views.reactivate_credit_card, name='reactivate_credit_card'),
    path('delete/<str:card_code>/', views.delete_credit_card, name='delete_credit_card'),

    # URLs relacionadas con cuentas
    path('register-account/', views.client_register, name='client_register'),
    path('login/', views.client_login, name='login'),
    path('accounts/', views.accounts, name='accounts'),
    path('profile/', views.profile, name='profile'),
    path('edit/', views.edit, name='edit'),
    path('account-details/<int:account_id>/', views.account_details, name='account_details'),
    path('add-money/<int:account_id>/', views.add_money, name='add_money'),
    path('edit-alias/<int:account_id>/', views.edit_alias, name='edit_alias'),
    path('deactivate-client/<int:client_id>/', views.deactivate_client, name='deactivate_client'),
    path('client/reactivate/<str:token>/', views.reactivate_client, name='reactivate'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

clients/views.py
import json
from django.utils.translation import gettext as _
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.crypto import get_random_string
from django.contrib.auth.hashers import make_password
from .forms import AccountRegistrationForm, AddMoneyForm, ClientEditForm, ClientRegistrationForm, CreditCardForm, CreditCardFormWithoutAccount, LoginForm, UserEditForm, UserRegistrationForm
from .models import Account, Client, CreditCard 
from transactions.models import Transaction

#######################################################



# Cuentas

@login_required
def register(request):
    current_account_count = Account.objects.filter(client=request.user.client).count()
    if current_account_count >= 3:
        messages.error(request,  _('Número máximo de cuentas excedido (máximo 3 cuentas).'))
        return redirect('home')

    if request.method == 'POST':
        form = AccountRegistrationForm(request.POST)
        if form.is_valid():
            user = authenticate(username=request.user.username, password=form.cleaned_data['password'])
            if user is not None:
                account = form.save(commit=False)
                account.client = request.user.client
                account.save()
                return redirect('home')
            else:
                messages.error(request, _('La contraseña actual ingresada no es correcta.'))
    else:
        form = AccountRegistrationForm()

    return render(request, 'account/register.html', {'form': form})

@login_required
def accounts(request):
    accounts = Account.objects.filter(client=request.user.client, status=Account.Status.ACTIVE)
    return render(request, 'account/accounts.html', {'accounts': accounts})

@login_required
def account_details(request, account_id):
    account = get_object_or_404(Account, id=account_id)
    transactions = Transaction.objects.filter(account=account).order_by('-timestamp')
    credit_cards = account.credit_cards.all()
    return render(request, 'account/account_details.html', {'account': account,'transactions': transactions, 'credit_cards': credit_cards})

@login_required
def add_money(request, account_id):
    account = get_object_or_404(Account, id=account_id)
    if request.method == 'POST':
        form = AddMoneyForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            if amount <= 1000000:
                if account.balance < 999999999.99:
                    account.balance += amount
                    account.save()
                else:
                    form.add_error('amount', _('La cantidad que ha puesto excede el límite que puede alvergar la cuenta.'))
                alias=account.alias
                balance=account.balance
                messages.success(request, _(f'Se han añadido {amount} euros a la cuenta {alias}. Balance actual: {balance} euros.'))
                return redirect('clients:account_details', account_id=account.id)
            else:
                form.add_error('amount', _('La cantidad no puede superar 1 millón de euros.')) 
    else:
        form = AddMoneyForm()

    return render(request, 'account/add_money.html', {'form': form, 'account': account})  
@login_required
def edit(request):
    if request.method == 'POST':
        client_form = ClientEditForm(
            instance=request.user.client, files=request.FILES, data=request.POST
        )
        print(request.FILES)
        user_form = UserEditForm(instance=request.user, data=request.POST)

        if client_form.is_valid() and user_form.is_valid():
            client_form.save()
            user_form.save()
            messages.success(request, _('¡ Perfil actualizado correctamente !'))
            return render(request, 'client/profile.html', {'profile': profile})
        else:
            messages.error(request, _('Error al actualizar tu perfil'))
    else:
        client_form = ClientEditForm(instance=request.user.client)
        user_form = UserEditForm(instance=request.user)
        print("\n\n\n\n\n\n\n\n\n   ",request.user.client)
        photo = request.user.client

    return render(
        request,
        'client/edit.html',
        {'client_form': client_form, 'user_form': user_form, 'photo': photo},
    )

@login_required
def edit_alias(request, account_id):
    account = get_object_or_404(Account, id=account_id)

    if request.method == 'POST':
        new_alias = request.POST.get('new_alias')
        account.alias = new_alias
        account.save()
        messages.success(request, _('El alias de la cuenta se ha cambiado correctamente.'))
        return redirect('home')
    else:
        return render(request, 'account/edit_alias.html', {'account': account})

@login_required
def deactivate_account(request, account_id):
    if request.method == 'POST':
        account = get_object_or_404(Account, id=account_id, client=request.user.client)

        if account.status == Account.Status.BLOCK:
            messages.warning(request, _('La cuenta ya está desactivada.'))
            return redirect('home')

        account.status = Account.Status.BLOCK
        account.save()

        reactivation_token = get_random_string(length=32)
        account.reactivation_token = reactivation_token
        account.save()

        subject = _('Reactiva tu cuenta')
        message = _(f'Pulsa en el enlace para reactivar tu cuenta: http://localhost:8000/es/reactivate/{reactivation_token}')
        from_email = 'your_email@example.com'
        to_list = [request.user.email]

        send_mail(subject, message, from_email, to_list, fail_silently=True)

        return redirect('home')

    return render(request, 'account/deactivate_account.html')

@login_required
def reactivate_account(request, token):
    account = Account.objects.filter(reactivation_token=token, status=Account.Status.BLOCK).first()
    
    if account:
        account.status = Account.Status.ACTIVE
        account.reactivation_token = None
        account.save()
        return render(request, 'account/reactivate_account.html', {'success': True})
    
    return render(request, 'account/reactivate_account.html', {'success': False})




#######################################################




# Tarjetas

@login_required
def credit_card_list(request):
    credit_cards = CreditCard.objects.all()
    return render(request, 'cards/credit_card_list.html', {'credit_cards': credit_cards})

@login_required
def credit_cards(request):
    account_id = request.GET.get('account_id')
    status = request.GET.get('status')

    accounts = Account.objects.filter(client=request.user.client)

    if account_id:
        credit_cards = CreditCard.objects.filter(account_id=account_id, status=status)
    else:
        credit_cards = CreditCard.objects.none()

    return render(request, 'cards/credit_cards.html', {'credit_cards': credit_cards, 'accounts': accounts})

@login_required
def add_credit_card(request):
    card_count = CreditCard.objects.filter(account__client=request.user.client).count()
    
    if card_count >= 4:
        messages.error(request, _('Has alcanzado el límite máximo de tarjetas de crédito.'))
        return redirect('clients:home')

    if request.method == 'POST':
        form = CreditCardForm(request.user.client, request.POST)
        if form.is_valid():
            credit_card = form.save(commit=False)
            credit_card.account = form.cleaned_data['account']
            pin = credit_card.pin
            credit_card.pin = make_password(pin)
            credit_card.save()
            codigo=credit_card.card_code

            send_mail(
                _(f'Tu tarjeta {codigo} ha sido creada con éxito'),
                _(f'Este es tu PIN: {pin}'),
                'your_email@example.com',
                [request.user.email],
                fail_silently=False,
            )
            return redirect('clients:credit_cards')
    else:
        form = CreditCardForm(request.user.client)

    return render(request, 'cards/add_credit_card.html', {'form': form})

@login_required
def add_credit_card_without_account(request, account_id):
    account = get_object_or_404(Account, id=account_id)
    card_count = CreditCard.objects.filter(account=account).count()

    if card_count >= 4:
        messages.error(request, _('Has alcanzado el límite máximo de tarjetas de crédito.'))
        return redirect('home')

    if request.method == 'POST':
        form = CreditCardFormWithoutAccount(request.POST)
        if form.is_valid():
            credit_card = form.save(commit=False)
            credit_card.account = account
            pin = credit_card.pin
            credit_card.pin = make_password(pin)
            credit_card.save()
            codigo =credit_card.card_code
            send_mail(
                _(f'Tu tarjeta {codigo} ha sido creada con éxito'),
                _(f'Este es tu PIN: {pin}'),
                'your_email@example.com',
                [request.user.email],
                fail_silently=True,
            )
            messages.success(request, _("Se ha creado la tarjeta con éxito"))
            return redirect('clients:account_details', account_id=account.id)
    else:
        form = CreditCardFormWithoutAccount()

    return render(request, 'cards/add_credit_card.html', {'form': form})

@login_required
def block_credit_card(request, card_code):
    card = get_object_or_404(CreditCard, card_code=card_code)
    
    if card.account.client.user == request.user:
        if card.status == CreditCard.Status.BLOCK:
            messages.error(request, _('Esta tarjeta ya está bloqueada.'))
            return redirect('home')

        card.status = CreditCard.Status.BLOCK
        card.save()

        send_mail(

clients/templates/client/dashboard.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Panel principal" %}{% endblock %}

{% block content %}
<style>
  /* Estilos para la guía del usuario */
  #userGuide {
    position: fixed;
    bottom: 20px;
    left: 20px;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 5px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    padding: 10px;
    z-index: 9999;
  }

  #userGuide h3 {
    margin-top: 0;
    font-size: 16px;
    color: #333;
  }

  #userGuide ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
  }

  #userGuide ul li {
    font-size: 14px;
    color: #666;
    margin-bottom: 5px;
    position: relative;
    padding-left: 20px;
  }


  /* Estilo para las acciones pendientes */
  .action-pending::before {
    content: "\2713"; /* Marca de verificación Unicode */
    color: #28a745; /* Color verde */
    position: absolute;
    left: 0;  }



  </style>

<div class="dashboard-container">
  <div id="mySidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    <details>
      <summary>{% trans "Acciones de Tarjetas" %}</summary>
      <a href="{% url 'clients:add_credit_card' %}">{% trans "Añadir Tarjeta" %}</a>
      <a href="{% url 'clients:credit_cards' %}">{% trans "Ver Tarjetas" %}</a>
    </details>
    <details>
      <summary>{% trans "Acciones del cliente" %}</summary>
      <a href="{% url 'clients:edit'%}">{% trans "Editar Perfil" %}</a>
      <a href="{% url "password_reset" %}">{% trans "Cambiar Contraseña" %}</a>
      <a href="{% url 'clients:deactivate_client' client_id=request.user.client.id%}">{% trans "Desactivar Cuenta" %}</a>
    </details>
    <details>
      <summary>{% trans "Acciones Cuentas" %}</summary>
      <a href="{% url 'clients:register' %}">{% trans "Registrar Cuenta" %}</a>
    </details>
  </div>

  <div id="main" class="main-content">
    <button class="openbtn" onclick="openNav()">☰ {% trans "Mostrar acciones" %}</button>
    <h1 class="dashboard-title">{% trans "Bienvenido," %} {{ user.username }}!</h1>
  </div>
  
  <div class="container">
    {% if messages %}
      <div class="messages">
        {% for message in messages %}
          <div class="{% if message.tags %}alert alert-{{ message.tags }}{% endif %}">
            {{ message }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
    <div class="row">
      {% for account in accounts %}
        {% if account.status == 'AC' %}
          <div class="col-md-4">
            <div class="card account-card">
              <div class="card-header">
                <h2><a href="{% url 'clients:account_details' account.id %}">{{ account.alias }}</a></h2>
              </div>
              <div class="card-body">
                <p>{% trans "Código:" %} {{ account.code }}</p>
                <p>{% trans "Balance:" %} {{ account.balance }}</p>
              </div>
              <div class="card-footer">
                <a href="{% url 'clients:edit_alias' account.id %}" class="btn btn-primary">{% trans "Editar alias" %}</a>
                <a href="{% url 'clients:deactivate' account.id %}" class="btn btn-danger">{% trans "Desactivar cuenta" %}</a>
              </div>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>

  <!-- Guía del usuario -->
  <div id="userGuide">
    <h3>{% trans "Guía para el usuario" %}</h3>
    <p>{% trans "Para disfrutar de la experiencia completa, realiza todas estas acciones:" %}</p>
    <ul id="actionList">
        <li class="action-pending">{% trans "Crea tu primera cuenta" %}</li>
        <li class="action-pending">{% trans "Asocia una tarjeta de crédito a tu cuenta" %}</li>
        <li class="action-pending">{% trans "Realiza tu primera transacción" %}</li>
    </ul>
    <div id="progressIndicator">
        <p>{% trans "Progreso:"%} <span id="progressCount">0%</span></p>
    </div>
</div>

</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var accountsExist = {{ accounts_json|safe }};
    var creditCardsExist = {{ credit_cards_json|safe }};
    var transactionsExist = {{ transactions_json|safe }};
    var totalTasks = 3; // Total de tareas
    var completedTasks = 0; // Inicialmente todas las tareas se consideran completadas

    // Comprobamos si existen cuentas, tarjetas de crédito y transacciones
    if (!accountsExist || accountsExist.length === 0) {
        document.querySelectorAll('#actionList li')[0].classList.remove('action-pending');
        completedTasks++; // Disminuir el contador de tareas completadas si existen cuentas
    }
    if (!creditCardsExist || creditCardsExist.length === 0) {
        document.querySelectorAll('#actionList li')[1].classList.remove('action-pending');
        completedTasks++; // Disminuir el contador de tareas completadas si existen tarjetas de crédito
    }
    if (!transactionsExist || transactionsExist.length === 0) {
        document.querySelectorAll('#actionList li')[2].classList.remove('action-pending');
        completedTasks++; // Disminuir el contador de tareas completadas si existen transacciones
    }

    // Calcular el progreso en función de las tareas completadas
    var progress = ((totalTasks - completedTasks ) / totalTasks) * 100;
    var roundedProgress = progress.toFixed(2); // Redondear el progreso a dos decimales

    // Actualizar el contador de progreso y la barra de progreso
    var progressCount = document.getElementById('progressCount');
    progressCount.textContent = roundedProgress + '%';

    var progressBar = document.getElementById('progressBar');
    progressBar.style.width = roundedProgress + '%';
});







// Función para abrir el menú lateral
function openNav() {
    document.getElementById("mySidebar").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
}

// Función para cerrar el menú lateral
function closeNav() {
    document.getElementById("mySidebar").style.width = "0";
    document.getElementById("main").style.marginLeft = "0";
}
</script>
{% endblock %}

clients/templates/client/deactivate_account.html
{% load i18n %}
<h1>{% trans "Cuenta desactivada" %}</h1>
<p>{% trans "Tu cuenta ha sido desactivada. Revisa el correo electrónico para obtener un enlace para reactivar su cuenta." %}</p>

clients/templates/client/edit.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Edita tu cuenta" %}{% endblock %}
{% block content %}
<div class="container-profile">
    <div class="container-fluid edit-profile">
        <h1>
            <strong>
                <b>{% trans "Edita tu cuenta" %}</b>
            </strong>
        </h1>
        <div class="row">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                    </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}

            <div class="col-md-3 imagen-edit">
                
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                <input type="file" name="photo" accept="image/jpg, image/png" id="photo-input" style="display: none;">
                <label for="photo-input">
                    {% if photo%}
                        <img src="{% thumbnail photo 180x180 %}" class="user-detail">
                    {% else %}
                        <img src="{% static '../media/no_picture.png' %}" class="user-detail" >
                    {% endif%}
                </label>
                <div class="col-md-3 info">
                    <strong><b>{{ user_form.as_p }}</strong></b>
                </div>
                <div class="col-md-3 info">
                    <button class="btn btn-primary button" type="submit">{% trans "Guardar"%}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/client/login.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
<head>
  <link type="text/css" href="{% static "css/style.css" %}" rel="stylesheet">
  
</head>
{% block title %} Log-in{% endblock %}

{% block content %}
  <div class="container">
    {% if messages %}
      <div class="messages">
        {% for message in messages %}
          <div class="{% if message.tags %}alert alert-{{ message.tags }}{% endif %}">
            {{ message }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
    <div class="row">
      <div class="col-md-6 offset-md-3 login-card">
        
        <div class="formulario-defecto custom-row">
          <h1 class="mt-4"> <strong> {% trans "Acceso" %} </strong> </h1>
          <hr>
        {% if form.errors %}
          <div class="alert alert-danger">
            {% trans "Su nombre de usuario y contraseña no coinciden. Inténtalo de nuevo." %}
            <a href="{% url "clients:client_register" %}" class="link">{% trans "Si no registrate aquí" %} </a>
          </div>
        {% else %}
          <p class="mt-4">
            <strong><b>{% trans "Por favor, utilice el siguiente formulario para iniciar sesión. Si no tienes una cuenta" %} <a href="{% url "clients:client_register" %}" class="link">{% trans "Registrate aquí" %} </a></b></strong>.
          </p>
        {% endif %}
          <form action="{% url 'login' %}" method="post" class="login-form">
            {% csrf_token %}
            <div class="form-group ">
              <strong><b>{{ form.username.label_tag }}</strong></b>
              {{ form.username }}
            </div>
            <div class="form-group">
              <strong><b>{{ form.password.label_tag }}</strong></b>
              {{ form.password }}
            </div>
            <input type="hidden" name="next" value="{{ next }}" />
          </br>
            <button type="submit" class="btn btn-primary"><strong><b> {% trans "Iniciar sesión" %}</strong></b></button>
          </form>
          <p class="mt-4">
            <a href="{% url "password_reset" %}" class="link">
              <strong><b>{% trans "¿Olvidaste la contraseña?" %}</strong></b>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
  <style>
    * {
      box-sizing: border-box;
    }
    
    html,
    body,
    .wrapper {
      height: 100%;
    }
    
    @keyframes rotate {
      100% {
        background-position: 15% 50%;
      }
    }
    
    body {
      place-items: center;
      margin: 0;
      padding: 0 24px;
      background-image: url("/media/background.jpg");
      background-repeat: no-repeat;
      background-size: cover;
      font-family: Arial, sans-serif;
      color: #000;
      animation: rotate 6s infinite alternate linear;
    }
    
    @media (width >= 500px) {
      body {
        padding: 0;
      }
    }
    
    .login-card {
      text-align: center;
    }
    
    @media (width <= 500px) {
      .login-card {
        margin: 0;
        width: 400px;
      }
    }
    
    .login-card > h2 {
      font-size: 36px;
      font-weight: 600;
      margin: 0 0 12px;
    }
    
    .login-card > h3 {
      color: rgba(0, 0, 0, 0.38);
      margin: 0 0 30px;
      font-weight: 500;
      font-size: 1rem;
    }
    
    .login-form {
      width: 100%;
      margin: 0;
      display: grid;
      gap: 16px;
    }
    
    .login-form > input,
    .login-form > button {
      width: 100%;
      height: 56px;
    }
    
    .login-form > input {
      border: 2px solid #ebebeb;
      font-family: inherit;
      font-size: 16px;
      padding: 0 16px;
    }
    
    .login-form > button {
      cursor: pointer;
      width: 100%;
      height: 56px;
      padding: 0 16px;
      border-radius: 0.5rem;
      background: #216ce7;
      color: #f9f9f9;
      border: 0;
      font-family: inherit;
      font-size: 1rem;
      font-weight: 600;
      text-align: center;
      letter-spacing: 2px;
      transition: all 0.375s;
    }
    
    .login-form > a {
      color: #216ce7;
      font-size: 1rem;
      text-align: left;
      text-decoration: none;
      margin-bottom: 6px;
    }
    
</style>
{% endblock %}

clients/templates/client/profile.html
{% extends "base.html" %} 
{% load thumbnail %} 
{% load i18n %} 
{% load static %}
{% block title%}{% trans "Perfil de cliente" %}{% endblock %} 
{% block content %}
<div class="container container-profile" style="width: 750px">
  <div class="profile">
    <h1 class="display-4">
      <strong
        ><b>{% trans "Perfil de" %} {{ profile.user.username }}</b></strong
      >
    </h1>
    <div class="row">
      <div class="col-md-4 imagen">
        {% if profile.photo %}
        <img src="{% thumbnail profile.photo 180x180 %}" class="user-detail"/>
        {% else %}
            <img src="{% static '../media/no_picture.png' %}" class="user-detail" >
        {% endif %}
      </div>
      <div class="col-md-5 info">
        <p class="lead mb-5">
          <strong><b>{% trans "Nombre de usuario:" %} </b></strong>
        </p>
        <p class="user">{{ profile.user.username }}</p>
        <p class="lead mb-5">
          <strong><b>{% trans "Nombre:" %}</b></strong>
        </p>
        <p class="user">{{ profile.user.first_name }}</p>
        <p class="lead mb-5">
          <strong><b>{% trans "Apellido:" %} </b></strong>
        </p>
        <p class="user">{{ profile.user.last_name }}</p>
        <p class="lead mb-5">
          <strong><b>{% trans "Correo electrónico:" %} </b></strong>
        </p>
        <p class="user">{{ profile.user.email }}</p>
      </div>
      <div class="profile_buttons">
        <form action="{% url 'clients:edit' %}">
          <button class="btn btn-primary" type="submit">
            {% trans "Editar perfil" %}
          </button>
        </form>
        <form action="{% url 'password_reset' %}">
          <button class="btn btn-primary" type="submit">
            {% trans "Cambiar contraseña" %}
          </button>
        </form>
        <form
          action="{% url 'clients:deactivate_client' request.user.client.id %}"
          method="post"
        >
          {% csrf_token %}
          <button class="btn btn-primary" type="submit">
            {% trans "Desactivar cuenta" %}
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

clients/templates/client/reactivate_account.html
{% load i18n %}
<h1>{% trans "¡Cuenta reactivada!"%}</h1>
<p>{% trans "Tu cuenta se ha reactivado. Puedes volver a iniciar sesión de nuevo." %}</p>

clients/templates/client/reactivate_account_failed.html
{% load i18n %}
<h1>{% trans "Reactivación fallida" %}</h1>
<p>{% trans " Disculpe, no podemos reactivar su cuenta. El enlace ha expirado o es invalido." %}</p>

clients/templates/client/register.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Crear una cuenta" %}{% endblock %}
{% block content %}
<div class="container">
    <div class="row ">
        <div class="col-md-6 offset-md-3">
            <div class="row custom-row formulario-register">
                <h1>{% trans "Crear una cuenta" %}</h1>
                <hr>
                <p><strong><b>{% trans "Por favor, regístrate utilizando el siguiente formulario:" %}</b></strong></p>
                <form method="post" enctype="multipart/form-data">
                    <strong><b>{{ user_form.as_p }}</b></strong>
                    {{ profile_form.as_p }}
                    {% csrf_token %}
                    <p><input type="submit" class="btn btn-primary" value={% trans "Crear mi cuenta"%}></p>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

clients/templates/client/register_done.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Bienvenido" %}{% endblock %}
{% block content %}
<h1>{% trans "Bienvenido/a" %} {{ new_user.first_name }}!</h1>
<p>
{% trans "Su cuenta ha sido creada satisfactoriamente." %}
{% trans "Ahora puedes" %} <a href="{% url "login" %}"> {% trans "iniciar sesión"%}</a>.
</p>
{% endblock %}